### ISSUE TITLE
Merge ops/ctl admin UIs

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#1009]
### Is your feature request related to a specific problem?

Now that the repos are merged, we'll need to update the front-end to let users navigate the full UI for both applications

### Describe the solution you'd like

A single navigation page for all UIs

### Additional context

We've already put in a request for a hifi design for this

**Comment by ThomasLaPiana** [comment]
@mfbrown any ETA on the hifi's here? This is ready for work at this point

**Comment by ThomasLaPiana** [comment]
@ssangervasi I've done another big upstream merge so this should be about ready to start

**Comment by ssangervasi** [comment]
This ticket covers a lot of tasks, depending on the scope of "A single navigation page for all UIs". I'll enumerate them here to start.

## 1. Configure Ops/Ctl zones
This step assumes we're going to run Ops and Ctl as two different Next apps (at least to start). This means they won't share any state and navigating between them reloads pages, like how the Data Map is hosted.

Tasks:

1. Each of the apps needs a Next basePath.
	- This is necessary to route the pages unambiguously.
	- Giving _both_ of the apps a basePath means we can use the top-level paths for an app this is truly unified.
	- Example: `/ctl/taxonomy`, `/ops/connection`
2. Each needs zone-aware navigation
	- [This PR](https://github.com/ethyca/fides/pull/1037) introduced zone configuration so that Ctl can link to Data Map. 
	- Ctl must update its config and nav links so that Ctl links are under the `ctl` base path, and introduce the `ops` base path.
	- Ops can copy in the `features/common/zones` code, then define its own `zone-config.ts` with the new base paths.
3. Each development server needs to run on a different port.
	- I think both default to `3000`. One needs to be different to serve both in dev.
	- Data Map already runs on `4000`.

 
## 2. Backend serves both sets of static files.
When running the app in production (built image) the unified backend needs to serve both UIs from the catchall route.

Tasks:

1. Each `copy-export` command needs to copy the static files into directories under `src/fides/`.
	- Currently, Ctl uses `src/fidesctl/ui-build/static` while Ops `src/fidesops/ops/build/static`.
	- Let's settle on `src/fides/build/static/[ops|ctl]`
2. The fides catchall route needs to serve both static directories
	- The [updated route map](https://github.com/ethyca/fides/pull/1046) should be able to handle multiple directories.
	- The base paths added in step 1.1 should allow us to figure out which directory goes with which page.
	- Definitely need to test fidesctl-plus after doing this.

## 3. Actual unification of the UIs
Up to this point, the tasks have just been to get both apps to play nice in the same sandbox. Now they have to be friends.

We have some options of how much we integrate the two UIs. These are listed from easiest to hardest (dev-wise).

1. Add a home/welcome page that directs the user to Ops or Ctl.
	- Each link describes what features each UI has.
	- User can go back to that page to switch apps.
	- Note that this is easy while transitioning to unification b/c we don't modify any of the content of the two UIs themselves.
	- Probably need to update the default index route in the backend. 
2. Context-aware app switcher.
	- A dropdown that lives in the nav bar or user button to switch from Ctl to Ops and vice versa.
	- Must be implemented in both UIs.
3. Nav bar with all the things.
	- Merge the two sets of nav bar links.
	- This means all the pages are a click away without the user having to differentiate the two apps.
	- Probably needs a design b/c that nav bar could get very wide. Are they grouped at all?
4. Full UI-nification
	- Create a new Next app that has Ops and Ctl rolled together.
	- This would really be its own epic.

**Comment by NevilleS** [comment]
Hey @ssangervasi - I think I follow most of the recommended steps there to do a gradual transition, but given that we've already forklifted all the client code into sibling directories, I'm wondering if we could at least _attempt_ to jump to option 4 to avoid the tech debt of additional routers, base URLs, multiple underlying Next apps, etc.

If we do a quick survey of the two app directories:
* https://github.com/ethyca/fides/tree/unified-fides/clients/ctl/admin-ui
* https://github.com/ethyca/fides/tree/unified-fides/clients/ops/admin-ui

We can see that the structure and basic files are the same, since they are from the same Next template and because we've copied some code from ops -> ctl in the past (like the "auth" pages). In particular, the `src/pages` directory for each have no folder conflicts, so that tells us the actual UI routes don't conflict at all. Similarly, the `src/features` directories are pretty compatible, except for the `src/features/common` folder that they both use, where there might be some merge conflicts to deal with.

Overall, though it seems to me that if we tried something like this, we'd probably find that there are just a handful of duplicates to tackle together across the two UIs:
1. Pick a "home" app to start from (e.g. `ctl/admin-ui`)
2. Merge the various folders together (`src/pages`, `src/features`, etc.)
3. Resolve any conflicts
4. Update the navigation bar to include the combined routes
5. Test the UI and create bugs for the issues
6. Fix the bugs

Is that viable? It's similar to your option 4, but intentionally skips 1-3 as those all would require us creating & temporarily maintaining more technical debt, which I doubt is the best use of our time right now

**Comment by NevilleS** [comment]
Note: you'll need someone to pair with from the Fidesops team. We can definitely get someone to help here!

**Comment by ThomasLaPiana** [comment]
cc @TheAndrewJackson

**Comment by NevilleS** [comment]
Also, sometimes a picture speaks volumes:
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/1834295/188933503-ceb55b5a-eca9-4057-b39d-4e200671309c.png">

We can rearrange the order of that unified nav and tweak the naming for each tab, but this _seems_ worth attempting to get us to that true goal of a single UI

**Comment by ssangervasi** [comment]
Yeah, I suppose I was pessimistic with how many conflicts there would be. (And the "A single navigation page for all UIs" made me think about navigating between two independent apps to start).

To clarify your step 1: initially merge everything into `ctl/admin-ui`, then as some final step we'd want to move that directory somewhere without the "ctl" prefix.

**Comment by NevilleS** [comment]
Yeah- if you do it that way (move to ct/admin-ui, then move to just admin-ui) you can preserve git history nicely by leveraging `git mv` a bunch!

I'm really assuming that much of the UI is very component-ized and isolated so this'll work relatively easily. That's an assumption though- I'd recommend just blocking out a day and seeing how far you get?

**Comment by ssangervasi** [comment]
With the all-in-one app approach, will still need some step-2-related changes. Adding in a few more [route map dirs](https://github.com/ethyca/fides/pull/1046) should make it possible to serve the static files with fallbacks.
