### ISSUE TITLE
Display DSR error details and log

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#1202]
### USER STORY

- As an admin I should be able to see what subject requests have encountered an error. Also it should be clear to me that the subject requests have NOT been executed on an error.
- As an admin, I must be able to see where the subject request errored and why it errored.

### REQUIREMENTS

- Subject requests that have encountered an error that has prevented the request from processing as expected, should stop processing and be moved to a “Errored” state (see Error Subject Request Criteria below)
- Track and display where a subject request error along with an error code that tells you why.

### AC

- When a DSR errors show an error status in the Subject Request tab
- Add "Request errored at connector" and "Request processing cancelled due to error" messages to the Details page
- Add error event details to the Details page
- Add error log to the side drawer of the Details page

### DESIGNS
User Flow:
[https://www.figma.com/file/4qgQpYc1bX4dXg2PHmRORL/DSR-Error-Handling?node-id=2%3A7179](https://www.figma.com/file/4qgQpYc1bX4dXg2PHmRORL/DSR-Error-Handling?node-id=2%3A7179)

Final Screens:
https://www.figma.com/file/MTbZohIGvB4bq2f2wkiDHO/Fidesops-Management-UI?node-id=4006%3A60640

**Extra info** - This was originally implemented but a regression has caused it to stop working somewhere along the lines, it’ll need to be investigated. In running fidesops (Oct 3) I see an error status in the Subject Request tab. There is more in the details page. - [Epic Requirements Doc](https://ethyca.atlassian.net/wiki/spaces/PM/pages/2374730475/DSR+Error+Handling)

**Comment by chriscalhoun1974** [comment]
@Kelsey-Ethyca When a user views the **Activity timeline** for a given DSR with an Error status, the following API endpoint gets invoked:

`/api/v1/privacy-request/{privacy_request_id}/log`

**Response body**


![Image](https://user-images.githubusercontent.com/68459950/198296308-28d36225-c5cc-4bf9-a2c0-564948528fdc.png)

Based on the requested Figma designs, there is acceptance criteria to embed the `<Datastore name>` in a hyperlink such as `Request errored at <Datastore name> connector`. Upon clicking this hyperlink, a brief summary of the event details should be displayed containing additional Datastore info. In order to meet this acceptance criteria, the API endpoint `/api/v1/privacy-request/{privacy_request_id}/log` needs to be updated to include the Datastore info in which the DSR request errored at. Having the **fides_key** (**dataset_name**) is not enough to retrieve the Datastore info from the API endpoint:

`/api/v1/connection/{connection_key}`

I would need at minimum the **connection_key** to be added to the existing API payload `/api/v1/privacy-request/{privacy_request_id}/log` . Then I could make a secondary API call to get the Datastore info. Ideally, making an additional API call is not optimal. 

I have investigated other shortcuts via the fides -Swagger UI. Unfortunately, this is a blocker for this issue currently.

**Comment by eastandwestwind** [comment]
@chriscalhoun1974 looks like in the mocks, we'll need both the datastore name and the datastore ID. Because of this, I'm thinking providing just the datastore connection key in the `/api/v1/privacy-request/{privacy_request_id}/log` endpoint, so that we can make an additional call to get connection details for render. 

This change will require a database migration, code changes to get connection key for every place where we create logs, and updating tests. I'm estimating 2-3 days of work, but in the meantime, the front-end structure can be mocked out to anticipate this data.

Thoughts @chriscalhoun1974 / @Kelsey-Ethyca ?

**Comment by chriscalhoun1974** [comment]
Found another additional API endpoint which will need to be updated too

`api/v1/privacy-request` GET

**Comment by eastandwestwind** [comment]
@chriscalhoun1974 mind creating a new ticket for BE work, if there isn't one already?

**Comment by chriscalhoun1974** [comment]
@eastandwestwind @Kelsey-Ethyca For the BE work, I have created the following [ticket](https://github.com/ethyca/fidesops/issues/1439).
