### ISSUE TITLE
Update GET Connections API endpoint (api/v1/connections) to include specific Saas types

### ISSUE THREAD

**Issue by chriscalhoun1974** [ethyca/fides#1276]
Currently, the user cannot search by a list of specific Saas types. The GET connections API route (api/v1/connection) does not include filtering by specific Saas types. The connection_type query string parameter should filter either specific ConnectionType or Saas types.

I have updated the Datastore Connection Management landing page to allow the user to filter specific Datastore Types. This includes Saas and Connection enum values. 

Please reference (GET api/v1/connection_type) for all of the available Connection Types.

![Image](https://user-images.githubusercontent.com/68459950/194604211-804edfe4-9855-4a36-921f-7a5820a7b14b.png)

**Comment by adamsachs** [comment]
i think you should be able to just pass in a `system_type=saas` query param? i might be missing something though

**Comment by sanders41** [comment]
The issue is he needs to search for specific saas connectors, `sentry` for example. So right now when he searches `sentry` he gets an error because it is not a `system_type`. [This](https://github.com/ethyca/fides/blob/63f1c506a8e0e5d022a9fd20e70259c62eb7a32e/src/fides/api/ops/api/v1/endpoints/connection_endpoints.py#L132) is where we need an update. We need to search `connection_type` and the saas_connection type if available.

**Comment by adamsachs** [comment]
thanks for the clarification @sanders41  - my friday afternoon brain read this too quickly, sorry about that!
