### ISSUE TITLE
Catch _every_ exception bubbled up by the CLI, to prevent showing stack traces

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#1474]
### Is your feature request related to a specific problem?

Our users get really ugly stack traces from the CLI whenever there is an error we haven't caught.

### Describe the solution you'd like

We should implement a "catch all" that handles any unexpected error, that then prints a generic `An error has occurred` message. We can then focus on gracefully handling all of the different errors our users encounter. Additionally, when `dev_mode` is enabled it should let the ugly errors and stack traces go through

### Describe alternatives you've considered, if any

Not sure what the other options are here reasonably. There will always be places we throw errors where we didn't expect to, so trying to catch every one pre-emptively seems unrealistic

**Comment by ThomasLaPiana** [comment]
@sanders41 considering we use `SystemExit` in a lot of places to have pretty, clean error output, I'm thinking the easiest way to do this is basically catch everything that _isn't_ a SystemExit?

Any other clever ideas here? Effectively we never want a user to see a stack trace form the CLI

**Comment by sanders41** [comment]
I think you are right about everything except the `SystemExit`, but I don't think there is an `except not SystemExit` type option to catch everything except that (at least I haven't seen one). The only way I can think to be sure we catch everything is to put an `except Exception` at the entry point of the script.

On a broader scope, doing this makes it next to impossible to debug user issues or for them to debug themselves because you never know what the real error is. Really, I don't have a good solution to this though, its kind of a no win situation, users don't like to see stack traces, and they don't like it when we can't help debug because we don't have a stack trace. I also realize I'm not saying anything you don't already know with this :smile:

**Comment by ThomasLaPiana** [comment]
I agree, it's the equivalent of a 500 error from a server, basically letting the user know they're SOL and to file a bug report but like you said, we're between a rock and a hard place here, although I do come down on the side of hiding the stack traces/implementation details (hence the issue haha)

Right, so we can do an `except Exception` and then do nothing if the type is `SystemExit` or something then
