### ISSUE TITLE
Can't Run Fides with Docker-Compose

### ISSUE THREAD

**Issue by pattisdr** [ethyca/fides#1538]
### Bug Description

There's a recently-introduced bug with the `FIDES__CONFIG_PATH` in the docker-compose file that prevents you from bringing up the server or the shell in local testing.

Introduced here:
https://github.com/ethyca/fides/commit/0061b1100f57e488fe27757fc181a0e7958e4f91

#### Steps to Reproduce

Run `nox -s dev` or `nox -s dev -- shell`

Both the `fides` and `worker` containers will fail to start, and you'll see a No config file found message in the logs. 

### Expected behavior

_A description of what you expected to happen._

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by NevilleS** [comment]
Dang, sorry about this! This was my change so I'll own fixing it up.

Unfortunately, of course, it works on my machine... I'm wondering if this specific feature is relatively "new" and maybe you have an older Docker version... in the Compose file, I changed the configuration to allow providing a `FIDES__CONFIG_PATH` override in the ENV, but fallback to a default option otherwise:
```
    environment:
      FIDES__CONFIG_PATH: ${FIDES__CONFIG_PATH:-/fides/.fides/fides.toml}
```

I'll check the docs a bit.

**Comment by NevilleS** [comment]
I believe this kind of variable expansion has been supported since at least compose v2:
* detailed docs: https://docs.docker.com/compose/compose-file/compose-file-v2/#variable-substitution
* release notes: https://docs.docker.com/compose/compose-file/compose-versioning/#version-2

I'm wondering if the lack of an explicit `version` on the compose file might cause this. @pattisdr can you send me your docker & docker compose versions?
```
docker --version
docker compose version
```

**Comment by pattisdr** [comment]
yep!

Docker version 20.10.18, build b40c2f6b5d
Docker Compose version v2.10.2

**Comment by pattisdr** [comment]
argh, my fault, I'd set a `FIDES__CONFIG_PATH=../../../../` set as an environment variable awhile back which makes sense why it couldn't find the config!

**Comment by NevilleS** [comment]
No problem @pattisdr glad we figured out the mystery!
