### ISSUE TITLE
Consolidate the `celery.toml` into a `[celery]` section of the `fides.toml`

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#1591]
### Is your feature request related to a specific problem?

We have multiple configuration files

### Describe the solution you'd like

We have a single configuration file, and celery has its own subsection within the TOML file. It is basically schema-less (we don't do any validation) so that users can pass arbitrary args through to celery

**Comment by NevilleS** [comment]
So, @RobertKeyser and I ran headfirst into this issue while trying to build a minimal Helm chart for `fides`. Right now if you _don't_ include a `celery.toml` for the webserver, it just starts up and hangs mysteriously.

@seanpreston this might be easier to explain live, but this is a major gotcha for webserver deployments right now

**Comment by ThomasLaPiana** [comment]
@NevilleS ah, that makes sense....I never would've guessed that was the issue though

is it runnable by disabling the worker?

**Comment by NevilleS** [comment]
OK @ThomasLaPiana, never mind - this isn't as urgent because of this: https://github.com/ethyca/fides/pull/1829

That PR fixes the actual root cause of the behaviour we found, which was that the default config was still attempting to connect to the Celery broker (Redis) unless overridden. With that new default in place, we can keep the priority of this enhancement a bit further out 👍

**Comment by ThomasLaPiana** [comment]
@NevilleS this is still planned as part of the "config refactor" epic, it actually isn't a large code lift but I agree it isn't a main priority either, the other config changes are a lot more important
