### ISSUE TITLE
Fides ctl postgres dataset annotation coverage tests are failing

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#1684]
### Bug Description

Quite suddenly and without a clear cause, the annotation tests for `postgres` have started failing.

### Additional context

On a change that is completely unrelated, it seemed to start failing: [link to failed job](https://github.com/ethyca/fides/pull/1655/commits/6bd842865fa6812665ce4c54ab56139c8d48f786)

This is the earliest one I could find, but there might be earlier ones

**Comment by NevilleS** [comment]
I think this might have a simpler answer based on my initial sniff test... when inspecting this, the failures are:
```
tests/ctl/core/test_dataset.py::TestDatabase::test_get_db_tables[postgresql]
tests/ctl/core/test_dataset.py::TestDatabase::test_generate_dataset_passes_[postgresql]
tests/ctl/core/test_dataset.py::TestDatabase::test_dataset_coverage_manifest_passes[postgresql]
```

I call that out because @ThomasLaPiana and I definitely were making some updates to the default test PostgreSQL schema in other PRs, like this: https://github.com/ethyca/fides/pull/1609/files#diff-b649d6f7bfd020601ed8c65679441f25e5fe3c986d95fda02b4ec15e4cd10169

I think one possible explanation is that these "external" tests don't run in CI unless you apply the `run-unsafe-checks` label and we weren't doing that.

**Comment by NevilleS** [comment]
Yeah- I think it's highly likely that this specific change is probably the culprit: https://github.com/ethyca/fides/commit/8dca712f56aeff45ed08d2027ee55c46925fb446#diff-40903abfea74cdf56cdcfa80faf9d9e3009325680ba84bfc8b54898cb90544a9R20

In that change, we mount a complex postgres schema to that image to use for testing, but this other test is not expecting to see such a complicated postgres schema, it's expecting just this one: https://github.com/ethyca/fides/blob/main/tests/ctl/data/example_sql/postgres_example.sql

**Comment by NevilleS** [comment]
I'm going to say that we should assign this to you @ThomasLaPiana for now rather than try to put a fix in place immediately. I lean towards option 2 above (e.g. `docker-compose.test_env.toml`) so we can optimize that env in general, but I also know we don't want to spend a *ton* of time on that yet.

I can also help with this a bit this sprint too, just not today!

**Comment by NevilleS** [comment]
(also, thanks @adamsachs for double checking this too!)

**Comment by ThomasLaPiana** [comment]
Thank you all!

Ok, I'll think more on this solution and ship a fix within the sprint 🙂
