### ISSUE TITLE
`fides deploy` sometimes fails due to Docker permissions errors

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#1691]
### Bug Description

A number of users have reported failures with `fides deploy up`, caused by docker not having the correct permissions to mount volumes in certain locations

**Comment by ThomasLaPiana** [comment]
As discussed with @NevilleS , a good solution here might be to copy the files into a directory in the current working directory and then mount the files from there. This would then also allow the user to update their `config.json` for the privacy center and transparently see what his happening.

This could then also get cleaned up as part of `fides deploy down`

**Comment by NevilleS** [comment]
Yeah, I think that would work well! In fact, many users might prefer to keep those files around and start editing them for themselves. The only part I think is problematic is the compose file itself- we do some clever tricks to ensure the version of the docker image pulled matches the installed CLI, but that can't work by default... I think we'd want to change the tagged image to the matching version when deploy is first run (eg instead of :sample, use :2.0.0 or whatever matches), and then when deploy down runs, give the user the option to either cleanup the temporary files or "eject" and edit them directly. After the first deploy, even a vanilla docker compose up will work just as well.

**Comment by ThomasLaPiana** [comment]
@NevilleS so we'd be injecting that version number into a yaml file and then writing it out? Interesting, that actually wouldn't be too hard, and would give them a valid sample to work off of like you said.

I think its still important to consider the UX in all of this too, most users aren't going to be docker power users, and might have no idea the kinds of bread crumbs are actually getting left on their system, so I want to prioritize letting the user know what the side effects of this command will be, how to run the cleanup, etc.
