### ISSUE TITLE
DSR Bulk Reprocess not working with 2.0 Demo

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#1710]
When running the Fides 2.0 demo via `pip install ethyca-fides && fides deploy up` bulk reprocessing of errored requests, after fixing the source of the error, only succeeds with 1 request, while putting the others into an unrecoverable state.

**Steps to Reproduce**
- Install the fides 2.0 demo as described above and run it via `fides deploy up`
- Login to the Fides admin UI
- Create a Mailchimp connector with info that will cause an error
- Submit 3 access requests on the privacy center 
- Approve the requests
- Disable the mailchimp connector
- Select all three errored requests
- Click "Reprocess" in the upper right.

You'll see that one request will process correctly, the other two will fail. If you try to reprocess them individually they show an error like the attached image.

![Image](https://user-images.githubusercontent.com/4807009/200381654-96fcc3d6-bedb-4d9a-afd3-08625785ae3e.png)

**Comment by Roger-Ethyca** [comment]
@mfbrown @sanders41 I was able to duplicate this issue. I have a screen shot but unable to post a video as I don't have a private loom account. 
![Screen Shot 2022-11-18 at 2 46 15 PM](https://user-images.githubusercontent.com/115798183/202789608-ea0c5e59-4094-48da-b4c0-fbe1903747f4.png)

**Comment by mfbrown** [comment]
One of the first things to figure out here is how to reproduce this in the `test_env`

**Comment by adamsachs** [comment]
i've made some substantial progress on identifying the problem here, writing down some notes for tracking.

- i've been able to reliably reproduce the problem using the described steps on a `fides deploy up` environment using `ethyca-fides` version `2.2.0`. the steps mention 3 privacy requests - i've found that only 2 are needed to consistently reproduce the problem
    - i've created a test script that automates all the manual steps mentioned in the issue to more easily reproduce the problem
    - as a note, in the course of my manual testing, i did see some less consistent errors that showed somewhat similar symptoms, likely race conditions. i haven't pinned any of those down, but it's worth noting that there may be some other edge cases/race conditions in this workflow that aren't the core issue that's mentioned here
- for the core issue here, the logs show the following error message indicating what's consistently causing one of the re-processed requests to error out: `ERROR [root] Instance <PrivacyRequest at 0xffff6d53cf40> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/14/bhk3)`
- some remote debugging and diagnostic logging has indicated to me that the underlying cause for the above error seems to be that in certain scenarios (see below), we're effectively executing `request_runner_service.run_privacy_request()` on two privacy request concurrently, even though we've got no worker configured and our `task_always_eager` celery config is set to `True`. 
    - from my knowledge, this is not a state we expect to be in, and so in that sense it's not surprising that it's causing the above error. i'll dig more into precisely why we're hitting that error in this state, but i want to make clear why we're hitting this unexpected state only with certain conditions.
- one contributing cause for this state seems to be that we're invoking privacy requests via an `async` endpoint, `bulk_restart_privacy_request_from_failure`. 
    - in cases where we invoke privacy requests from sync endpoints, e.g. `approve_privacy_request`, we're not running into this problem.
    - i've also confirmed this hypothesis by temporarily switching `bulk_restart_privacy_request_from_failure` into a sync endpoint, and i did not see the problem. i don't know if this is a viable solution, and it does not feel like the _correct_ solution to me, but it's worth noting.
- another contributing cause for this state comes from the fact that our async endpoints actually need to get to a blocking call such that the current task is suspended. as far as i can tell, the only time this happens in general request execution is during the `analytics.send_analytics_event()` call to `fideslog`.
   - this explains why we only see the problem in a `fides deploy up` environment, and not in `nox -s test_env` or `nox -s dev` environments: the `fides deploy` environment does not necessarily opt out users from analytics;  whereas the other dev environments do, by default, opt out of analytics, which in turn bypasses the call to `fideslog` and means our task is never suspended.
   - as soon as the task for one re-processed privacy request is suspended on the `analytics_client.send_async` call, the other privacy request begins its `request_runner_service.run_privacy_request()` execution.
   - i believe what then happens is that the same `DatabaseTask` that manages the db session is being used concurrently, which is not expected. as the "first" request resumes and then wraps up execution, the session is cleaned up (likely closed), and it's never explicitly re-opened on the _other_ request task, since that's also being resumed mid-execution.


i'm still not exactly sure the best path forward, but at least this is a start to understanding what's going on and why it's only happening in certain circumstances.
