### ISSUE TITLE
Add UI version indicator to dev UI

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fides#1972]
It'd be very useful for the UI to show which build version it's running in dev mode.

**Comment by allisonking** [comment]
Is there a reason to do this only in dev mode and not also in prod? It might be useful in prod as well since it's often when people try to go to localhost:8080 that it turns out they're not on the right fides version. 

There are a few options of where we could put this:
* As a tooltip over the fides logo (hidden, you'd have to know to hover there to see it)


![Image](https://user-images.githubusercontent.com/24641006/210394983-4b4af77c-7200-4b6a-9b09-e441085775c9.png)


* Some copy under "Welcome back"?



![Image](https://user-images.githubusercontent.com/24641006/210395602-19361f7b-3489-4bbb-bfd1-7c3935785bf2.png)

* Something in the account dropdown?



![Image](https://user-images.githubusercontent.com/24641006/210395993-b38bf6b0-9dc8-46a3-92ab-ba6dbd87e88f.png)

Thoughts, @seanpreston or @rsilvery ?

**Comment by rsilvery** [comment]
I'm a big fan of having this in prod too. It will help hugely with customer support.

**Comment by rsilvery** [comment]
@allisonking from Slack with design, profile/signout menu is fine! https://ethyca.slack.com/archives/C0114BAK160/p1672847452335619

**Comment by rsilvery** [comment]
Scratch that. I think we need to just stick with dev for now. We'd need design (per Mala) to put this in and they just don't have the cycles for this right now.

**Comment by seanpreston** [comment]
I much prefer the account dropdown, thanks for the options @allisonking

**Comment by allisonking** [comment]
After talking to @adamczepeda , as a stop gap until design has more time to think about this, we're going to stick the version number in the account dropdown, but make it look a lil lighter so it doesn't look as much like a button. This will be available in prod too 👍
