### ISSUE TITLE
Okta scan UI flow flash

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fides#1977]
@rsilvery has noticed some [odd behaviour in the Okta / AWS system scan flows](https://ethyca.slack.com/archives/C04471211FE/p1670008948877879).

To recreate:
1. Do an Okta or AWS scan to add systems using new /add-systems route
2. Register systems
3. UI will quickly jump back to this window before forwarding on to the data map:

The UI should not jump before forwarding to the datamap.

**Comment by allisonking** [comment]
This is likely because of https://github.com/ethyca/fides/blob/main/clients/admin-ui/src/features/config-wizard/ScanResults.tsx#L61-L71

navigating to the datamap is slow because it's a totally different UI. in the mean time, we reset the config wiz state back to the beginning so it's ready for the next time someone wants to go through this flow. so the reset happens, then the datamap finally gets rerouted to. there are probably a number of ways to work around this, but it'd require a bit of thought

**Comment by allisonking** [comment]
I'm struggling to think of a reasonable solution. The general problem is:

1. User goes through the add system flow. These steps are persisted in redux so that the user can go back to where they left off in the flow (this was particularly useful when this was the config wizard. IMO it's less useful now that it's just another page...)
2. [These few lines](https://github.com/ethyca/fides/blob/main/clients/admin-ui/src/features/config-wizard/ScanResults.tsx#L61-L71) reset the steps back to the beginning so that when the user wants to add systems again, they aren't stuck at the last step. 
3. This works great when we are navigating to a page in the same zone (i.e. the systems page) because the state gets reset after the router is done routing.
4. However, this doesn't work great when we are navigating to a page outside the zone (i.e. the datamap UI). I'm guessing the router issues the request to route, then resets the state. The router has no control over the datamap UI's route, so we end up seeing the flashing described here—the state is reset first, _then_ we navigate (it's probably also slower to navigate out of the zone)

The easiest thing would be to not persist steps between the add system flow, but that might be a significant change to UX. Otherwise, maybe there's a way for, when we route _back_ to the admin UI from the datamap UI, to reset the step state? Might need to call on resident interzone navigator @ssangervasi , is there an idea I'm overlooking?

**Comment by allisonking** [comment]
Here's a video of what's happening. With the new nav changes, the flash looks slightly less bad than before now that we don't have that "generate your data map screen" anymore



https://user-images.githubusercontent.com/24641006/210881505-dac18df8-5391-4e0d-9f5f-018d9209a90d.mov

**Comment by allisonking** [comment]
@ssangervasi and I looked into this, and I think the flash actually looks pretty reasonable now with the combination of nav v2 and if we serve it on prod instead of dev (which makes things snappier)

Here's a video with the built fidesplus image:


https://user-images.githubusercontent.com/24641006/211097010-32cf0310-5c67-4237-97e9-04d2351336f3.mov

The alternative would be to, instead of clearing state when we navigate away, to set a flag before we navigate away, and then clear state based on that flag the next time the "add systems" page loads. The downside of this is that we'd likely get a flash when returning to "add systems", regardless of if we are coming in from the datamap UI or the admin UI. 

I'm tempted to mark this as a wontfix if you think the video looks okay @rsilvery ? Otherwise I can implement the "reset state on load" method. This is an unfortunate outcome of our separate zones for our UIs 🥲

**Comment by rsilvery** [comment]
Hmm.. @mfbrown  thoughts? It's fine by me.

**Comment by mfbrown** [comment]
Agreed - if what is shown in the recording is what we release with, that's totally fine with me.
