### ISSUE TITLE
The `no config file found` message is unclear for new users

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#2164]
### Is your feature request related to a specific problem?

The CLI will no longer write out a `fides.toml` be default whenever it is run, this leads to users seeing the `no config file found` message every time they run the CLI without a clear idea of why that is the case.

### Describe the solution you'd like

We should update the message to include mention of the `fides init` command that will write out the config file

### Describe alternatives you've considered, if any

This would primarily be hit by people running `fides deploy` for the first time, maybe we could make it a default part of the `fides deploy up` codepath?

### Additional context

This was introduced with Fides 2.4.0

__EDIT January 14, 2023__: We've decided that the execution plan is to remove the warning completely. More details in the comments

**Comment by rsilvery** [comment]
@NevilleS , @ThomasLaPiana can we switch back to the more user-friendly method of defaulting to generating this and providing a helpful error if they don't have write permissions?

**Comment by NevilleS** [comment]
Here's another option to consider: we don't need to "warn" the user at all, we can just remove the message.

With few exceptions, are we at the point now where most CLI commands can be run without a config file entirely? Exceptions would include `fides webserver` which does have some mandatory settings that we can't provide defaults for, but otherwise I feel the message itself may be completely unnecessary...

**Comment by NevilleS** [comment]
To summarize my understanding: the `No config file found` message appears on every CLI invocation, which we can solve by:
1. Switching back to the behaviour to create a config file by default
2. Changing the message to be more helpful (e.g. "Using default configuration values (run 'fides init' to create a fides.toml to change these!)")
3. Removing the warning message entirely (ie. silently use default configuration values)

Is that about right?

**Comment by rsilvery** [comment]
What are the CLI commands (or UI components) that can't be run without this file? Maybe it makes sense to generate these when those are used?

**Comment by NevilleS** [comment]
Actually I wasn't super precise about that: the file itself should *never* be required, even for `fides webserver` which (should be) the only command that needs config settings to run. You can provide those settings via environment variables instead.

I'd very much like to keep the behaviour of _not_ writing the file out as a side-effect of running CLI commands, because it's behaviour that has caused some deployment pains a few times for us... so if option 2 or 3 is doable, that'd be my preference!

What do we think: is it reasonable to just remove the warning entirely? Do we really need to guide users to create a file if it's unnecessary for most usage?

**Comment by rsilvery** [comment]
I feel like I'm still missing something. Are there any cases where not having this file would block a user from doing anything in the UI or CLI? If not let's fix the right problem!

**Comment by ThomasLaPiana** [comment]
@rsilvery Nope, this file is _never_ required. There are certain configuration values that _are_ required to run the webserver, but those can be set via environment variables.

The simplest solution to me seems like removing that "warning" altogether. If a user tries to run the webserver without the necessary values we handle that separately and let the user know. 

Currently I am not sure if the "warning" is actually serving much of a purpose other than letting the user know that they _could_ be using a configuration file.

**Comment by rsilvery** [comment]
Yes, this makes sense to me. Thank you both for patiently explaining :)
