### ISSUE TITLE
Search field on privacy request page isn't working 

### ISSUE THREAD

**Issue by Roger-Ethyca** [ethyca/fides#2270]
### Bug Description

Search field on the privacy request page isn't searching for anything. 

#### Steps to Reproduce

1. Log in to the UI and navigate to the Privacy request page.
2. Have a few requests in various states New, completed, denied and error
3. Using the search field look for any of the requests. 

### Expected behavior

The searched DSR or Erasure request should be displayed. 

![Screen Shot 2023-01-18 at 1 51 06 PM](https://user-images.githubusercontent.com/115798183/213268881-55979365-3bc8-4680-b663-03d153f4a680.png)

![Screen Shot 2023-01-18 at 1 51 44 PM](https://user-images.githubusercontent.com/115798183/213268911-45ede0a4-694e-40e9-ae25-975faaa2725f.png)

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by chriscalhoun1974** [comment]
@Roger-Ethyca @mfbrown @Kelsey-Ethyca Currently, the search field will bring any results based on Request Id value. The API endpoint uses a LIKE clause statement. Thoughts on changing this current behavior?

**Comment by Kelsey-Ethyca** [comment]
I will defer to @mfbrown for the final decision. My two cents are that today it is unclear what is being searched and there are two ways to fix this..
1. If we want to leave the placeholder saying "Search" it should search all fields that do not already have a filter (days left, request type, subject identity, and reviewed by). This will require backend work and could cause performance issues if the DSR list is incredibly long. 
2. If we want to search request id only, removing status because there is already a status filter, we should update the search placeholder to say search "Search Request ID". Maybe consider reordering the filters and search to match the order of the column headers. This will still require a small bit of backend work but less likely to cause any performance issues.

**Comment by Roger-Ethyca** [comment]
![Image](https://user-images.githubusercontent.com/115798183/219103769-d02151b9-7d6f-4a2f-bcca-0375cccf4dc3.png)
