### ISSUE TITLE
Missing latest image tags on privacy center and sample app

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fides#2301]
### Bug Description

We should be publishing a `latest` tag for each of these

#### Steps to Reproduce

See the latest release

### Expected behavior

`latest` images should be published

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by NevilleS** [comment]
I spotted the root cause of this @SteveDMurphy... it's a bug right here: https://github.com/ethyca/fides/blob/67a50d16d97030d9bd7afb18b417db68209dc8be/noxfiles/docker_nox.py#L215

Quite literally that should say `privacy_center_latest = f"{PRIVACY_CENTER_IMAGE}:latest"`, it's clearly what the author intended for that variable but messed it up.

(I'm pretty sure that author was me, by the way)

**Comment by SteveDMurphy** [comment]
Thanks @NevilleS ! I was looking at DockerHub quick and it appears `dev` might get cut a little more regularly and be in line with publishing a bleeding edge style image (so you should be in the clear here!)

In the end we will definitely want to do some renaming but it might make sense to keep the `dev` image and include a `latest` just for published tags

**Comment by SteveDMurphy** [comment]
Looked more closely this morning and the dev ones were separate and just above 🤦🏽 thanks for tracking this down @NevilleS !
