### ISSUE TITLE
Serve the flag icons from Fides/privacy center

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#2361]
The mobile phone input flag icon is coming from a 3rd party domain. Let's have this served from the privacy center like the other logos.

![Image](https://user-images.githubusercontent.com/4807009/214630431-ea3ab514-4b76-4d10-acb7-453533999181.png)

**Comment by Kelsey-Ethyca** [comment]
Currently pulling flags from https://gitlab.com/catamphetamine/country-flag-icons

**Comment by ssangervasi** [comment]
Note that it's not "the flag icon" as in the US flag, but an icon for every country. 

The quickest hack is to bundle them into the app: [including all flags](https://www.npmjs.com/package/react-phone-number-input?activeTab=readme#:~:text=./%3E-,Including%20all%20flags,-Linking%20flag%20icons). I think this is fine because we have Next doing the build which chunks assets automatically.

**Comment by Roger-Ethyca** [comment]
Verified on UAT
