### ISSUE TITLE
Fides Version Incorrectly populating

### ISSUE THREAD

**Issue by nicolas-ethyca** [ethyca/fides#2548]
### Bug Description

Fidesplus version showing incorrect version

#### Steps to Reproduce

1. Clone version
2. Navigate to management tab.

### Expected behavior

It shows proper version

### Screenshots

_If applicable, add screenshots to help explain your problem._
![image](https://user-images.githubusercontent.com/111306317/217847667-e5015db4-b31a-4408-b06f-eb7b5e2b5a85.png)

### Environment

* Version: 2.5.1-encoders
* OS: Max OSX
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by seanpreston** [comment]
Hey @nicolas-ethyca I've done some digging into this today, it's a quirk of how tagging works in git:
- a tag is a reference to a commit SHA
- `git describe --tags` will return the most recent tag accessible from the current checked out branch
- our release tags are created on the release branches
- `main` (or branches off) can't ever reach those release branches
- so can't return the most up to date version
- when running from a published docker image, or installed via `pip`, it will still always return the correct version because that tag _is_ accessible from that branch

There are some workarounds for this — for instance we could move away from using `.git`'s latest tag as the version indicator — I don't see this as a high priority for now since customers will always be running from a tag.

Does all that make sense?
