### ISSUE TITLE
Replace `get_config` in most places with importing `CONFIG` directly

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#2611]
### Is your feature request related to a specific problem?

lots of (almost every?) source file includes `CONFIG = get_config()`. This makes it hard to track down what needs to call `get_config()` with different arguments as opposed to just needing the config

### Describe the solution you'd like

replace almost all instances of `CONFIG = get_config()` with `from fides.core.config import CONFIG`

**Comment by pattisdr** [comment]
Just wanted to surface this separate work that Adam is doing to allow configuration variables to be updated without re-deploying.  His work involves accessing a ConfigProxy variable instead of the Config variable, where the ConfigProxy is combining the traditionally-set config with api-set config. https://github.com/ethyca/fides/pull/2551

This might just be a source of code conflicts to resolve is all.

**Comment by ThomasLaPiana** [comment]
Oh that's very interesting, thank you for the heads up! I'll have to look through and see what it might affect
