### ISSUE TITLE
Add a `fidesctl init` command

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#276]
Right now there is a decent amount of boilerplate that could be simplified with the addition of a `fidesctl init` command. Here are some of my thoughts for how this should work:

* the command looks like `fidesctl init <project_name>
* creates a directory called "fides_resources"
* maybe writes out the default taxonomy into manifest files?
* creates a generic `policy.yml`, `system.yml` and `dataset.yml` file that uses the provided project name to do some basic templating, or triggers the interactive "choose a policy", "build a system" type stuff

I think this command would make it easier to get started and make it more apparent what users are expected to create/maintain.

**Comment by PSalant726** [comment]
@ThomasLaPiana 

> Right now there is a decent amount of boilerplate that could be simplified

What boilerplate actions would be included, specifically? Is it best to put all of this behind a new `init` command, which would still need to be manually executed, or rather as prefix logic within _every_ command (that can detect when it's not needed and bail out)? Maybe both?

> - creates a directory called "fides_resources"

I've been thinking for a while that we should scope all long-lived fides-related files (manifests, config, etc.) within a `.fides` directory by default. At least adopting the `.` prefix would better align it with other tools that require repo-specific configuration/annotation. I'm thinking a simple structure like:

```
project_repo/
└── .fides/
    ├── datasets/
    │   └── dataset_1.yml
    ├── policies/
    │   └── policy_1.yml
    ├── systems/
    │   └── system_1.yml
    └── fidesctl.toml
```

By dictating the name of this directory + it's structure (instead of allowing users to define it) we enable simpler handling and manipulation of it's content within or own code, including requiring fewer arguments to the new `scan` command. Also, we could later extend this to include any fides-related files, including those required by fidesops, fideslang, etc. I'm not sure what we, or fidesctl users, gain from having the flexibility to define the name of this directory themselves. Thoughts?

> - maybe writes out the default taxonomy into manifest files?

What would these manifest files be used for? (not snarky, I'm curious)

> - creates a generic `policy.yml`, `system.yml` and `dataset.yml` file that uses the provided project name to do some basic templating, or triggers the interactive "choose a policy", "build a system" type stuff

I'm strongly opposed to this feature, and the second half of your sentence is some of the reason why. We have (and are slated to build) other tools that handle manifest generation. More significantly I think that this prescribes the content of the directory as a side-effect of executing "boilerplate" (required?) logic. Any files we create _without_ using `generate` commands would need heavy manual editing and would otherwise just be bloat. But, if we _did_ use those `generate` features within an `init` command, it would be redundant (and possibly unexpected behavior for a new user). I'd rather see us just create the directory/subdirectories, and print a message like:

```
Created a .fides directory at the repository root.

Configure fidesctl by modifying:
	project_root/.fides/fidesctl.toml

To learn more about configuring fidesctl, see:
	https://ethyca.github.io/fides/installation/configuration/

Generate manifest files using:
	fidesctl generate [dataset, policy, system]

To learn more about automated manifest file generation, run:
	fidesctl help generate
or, see:
	https://ethyca.github.io/fides/cli/#fidesctl-generate-dataset
```

**Comment by SteveDMurphy** [comment]
I dig what @PSalant726 mentioned as far as using it to drive usage of the `generate` and `scan` commands as well as the `.fides` pattern, however I still think `fidesctl init` has a place when looking at lowering the bar to entry as much as possible. With the expected expansion of adding fields to the organization manifest, this seems like a great opportunity to generate some useful data early with a well known command that is used more widely, familiarity could be helpful for us here in lieu of only having something like `fidesctl generate organization`

As far as the boilerplate, having an option to build sample manifests that allow someone to get comfortable with executing commands could be another way to help get people confident quickly. At the same time, leaving it optional gives us the chance to highlight the generate / scan commands like mentioned above. Further, as we add other features and gain an idea of usage with the init command we can use it as a way to chain other features that users find valuable as part of getting started (i.e. adding credentials to scan or generate your first dataset)
