### ISSUE TITLE
New user with full permissions can not add new systems 

### ISSUE THREAD

**Issue by Roger-Ethyca** [ethyca/fides#2769]
### Bug Description

New user with full permissions can not add new systems 

#### Steps to Reproduce

1. log in with root_user
2. create a new user with all permissions
3. log out of root_user
4. log in with the new user. 

### Expected behavior
New user should have permissions to add new systems

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by NevilleS** [comment]
Thanks - this is a good catch and (on retrospect, of course) it's an obvious issue with the UI permissions we added in 2.8.0. The impact of this is that _any non-root user_ created via the Admin UI will be unable to access the following routes:
* "View map", /datamap
* "View systems", /system
* "Add systems", /add-systems
* "Manage datasets", /dataset
* "Classify systems", /classify-systems
* "Taxonomy", /taxonomy

The root cause of this is that we did not have an existing scope in the UI that was a natural fit for these routes, so we implemented this using the `CLI_OBJECT_*` scopes (read, create, update), but those cannot be assigned via the UI. So the net result is that we inadvertently are locking users out of pages that they can use.

Since we're in the progress of migrating away to a simpler role-based permissioning system, the right call here is to disable the UI route restrictions right now while we work through that.

Note, for backwards compatibility, the only "safe" scopes to use are ones that are currently assignable via the UI, which are:
```
PRIVACY_REQUEST_READ,
PRIVACY_REQUEST_REVIEW,
PRIVACY_REQUEST_RESUME,
CONNECTION_READ,
CONNECTION_CREATE_OR_UPDATE,
CONNECTION_INSTANTIATE,
CONNECTION_TYPE_READ,
CONNECTION_DELETE,
CONSENT_READ,
DATASET_CREATE_OR_UPDATE,
DATASET_DELETE,
POLICY_READ,
POLICY_CREATE_OR_UPDATE,
USER_READ,
USER_CREATE,
USER_UPDATE,
USER_DELETE,
USER_PASSWORD_RESET,
USER_PERMISSION_CREATE,
USER_PERMISSION_UPDATE,
USER_PERMISSION_READ,
PRIVACY_REQUEST_UPLOAD_DATA,
PRIVACY_REQUEST_VIEW_DATA,
WEBHOOK_CREATE_OR_UPDATE,
WEBHOOK_READ,
WEBHOOK_DELETE,
```
