### ISSUE TITLE
Automatically apply GPC preferences when Fides.js is initialized

### ISSUE THREAD

**Issue by eastandwestwind** [ethyca/fides#3262]
Automatically apply GPC preferences when Fides.js is initialized.

- Send preference downstream (can mock API call for now)
- Preference is reflected in Fides cookie

**Comment by NevilleS** [comment]
> A. If no experience applies for the user + location, we cannot send GPC-override preference downstream as there are no notices to attach preference to.

Makes sense. However this is one of the reasons why I believe we need some "global default notices", which I've flagged as a separate follow-up with @mfbrown so we can design that too.

> B. If some kind of configuration option is invalid, we cannot obtain details to fetch experience / location, and also cannot send GPC-override preference downstream.

Yeah, if there's an error, we'll have to just fail.

> C. If consent overlay is disabled (we have this as a global config option), do we still attempt to retrieve experience / user location, and send GPC-override preference downstream? Probably not, because the disabled state represents the entire ecosystem of the overlay, so we shouldn't attempt any side-effects.

Disagree (politely!) on this one. The GPC signal should be honoured even if there is no overlay experience at all - in fact, what complicates GPC a bit is that it should work even if only a privacy center experience is configured...

So I think overall the GPC logic should be handled outside of the component-specific overlay bits. In other words, in the `Fides.init()` method and not part of `initOverlay` or the `<Overlay>` component, etc.

> D. Along the same vein, if consent overlay is disabled, should we generate a device id (for new users) and save the cookie?

Yes, we should save the cookie if we save the GPC preferences due to GPC. That does complicate the lifecycle of the cookie a bit... I think the cleanest logic is likely:
1. Always `getOrMakeFidesCookie()` in the `Fides.init` setup
2. Do not immediately save the cookie to the browser, though, just keep it in memory
3. Save the cookie as soon as a preference is saved (or, in the case of the privacy center, as soon as a new consent request is started which might require identity verification, etc.)

That's essentially "lazy-saving" the cookie, which is a pattern that makes sense to me here.

**Comment by eastandwestwind** [comment]
> So I think overall the GPC logic should be handled outside of the component-specific overlay bits. In other words, in the Fides.init() method and not part of initOverlay or the <Overlay> component, etc.

I'm planning to [fetch experiences / geolocation within](https://github.com/ethyca/fides/pull/3316/files#diff-3c4904558a00d0c4b432c838a8695f4255e0b0b2218ddc02937495aecc80e4f1R250) `initOverlay`, which would be a dependency for GPC. This signals to me that I'll need to extract this logic out of initOverlay to live in `Fides.init()` instead.

> Do not immediately save the cookie to the browser, though, just keep it in memory
To keep it in memory such that the PC can access it, too, you think it's OK to place it on the `window.Fides` obj that's created as part of `Fides.init()`?
