### ISSUE TITLE
Fix styling issues with consent modal

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#3423]
### Bug Description

The current styling of the modal is very functional/WIP:
<img width="1001" alt="image" src="https://github.com/ethyca/fides/assets/1834295/a7fa4d85-a3eb-4846-a610-86567cd6e191">

This needs a solid polish pass to bring it up to our goal:
<img width="649" alt="image" src="https://github.com/ethyca/fides/assets/1834295/148d2a3c-246b-4190-9344-13691f9db25b">

### Expected behavior

Lots of individual details, but the most significant are:
- [ ] Font
- [ ] Padding
- [ ] Borders
- [ ] etc.

Check out the stylesheet here: https://www.figma.com/file/dmEwdK3xZwjKfGVQ9t66xe/Fides-v.2-Master-Working-Files?type=design&node-id=6967-209288&t=Y5Krqi13KhRxafU9-0

**Comment by allisonking** [comment]
Hmm there must be some browser compatibility / other sneaky stuff going on here.

When I visit `fides-js-demo.html` in chrome:


![Image](https://github.com/ethyca/fides/assets/24641006/5bb2cf35-d5b4-4b63-96c1-328ad75a4388)

But when I visit in firefox 🙀 



![Image](https://github.com/ethyca/fides/assets/24641006/cda6bd3a-66d1-4234-8fc0-0987a136626c)

And Safari 🙀 



![Image](https://github.com/ethyca/fides/assets/24641006/17da7366-16df-4d7a-91d9-433662a1c36b)

**Comment by allisonking** [comment]
Okay for firefox and safari, I think this is because I was using [css nesting](https://developer.chrome.com/articles/css-nesting/) which turns out [isn't widely supported](https://caniuse.com/css-nesting)

in order to use css nesting, I think we'd need to add a css processor to rollup. it might be easier to unnest everything instead. nesting is nice because it keeps the css a bit cleaner/logical, but we could live without it.

still investigating the diff between the cookie house modal and the demo page modal though... stay tuned!

**Comment by allisonking** [comment]
Closed by https://github.com/ethyca/fides/pull/3429

**Comment by Roger-Ethyca** [comment]
moving to done
