### ISSUE TITLE
Errors when creating generic email connectors

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#3534]
When trying to create generic erasure or consent email connector I get `value is not a valid email toast` error when in fact it is. Test email is really mandatory although not marked as such BUT once populated we get a new error `Must supply at least one identity_type. `

create a connector in the old way > fill out the form with valid email not populating test email > click Save > see valid email error > populate test email > click Save > it works!

create a connector in the system integration > fill out the form with valid email not populating test email > click Save > see valid email error > populate test email > click Save > see identity_type error

![Image](https://user-images.githubusercontent.com/101993653/245190524-15d1af04-77b3-4366-a5ea-45622738a287.png)

**Comment by eastandwestwind** [comment]
Update- was able to reproduce the `value is not a valid email` error. The issue is the FE passes in `""` for `test_email_address` which it should pass in `null` if not provided by the user. 

After using `null`, the 2nd error `Must supply at least one identity_type.` could not be replicated, both in Postman or in the UI.

**Comment by Kelsey-Ethyca** [comment]
![Image](https://github.com/ethyca/fides/assets/101993653/cbe1337e-4f77-4823-846b-e9196256e63d)
