### ISSUE TITLE
Audit connector form fields to verify which are required

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#3537]
AC
- confluence doc with the connectors that are missing or unnecessary required field indicators

**Comment by galvana** [comment]
Hi @rsilvery, the missing piece here is that we don't have a UI design pattern to indicate "either or" inputs. For example, the Postgres connector allows the user to define a complete URL or the individual components that make up the URL (host, username, password, database name, etc). Since each of these fields can be optional based on the presence of other data the end result is that no field is flagged as required.


![Image](https://github.com/ethyca/fides/assets/2092272/db547f9e-c9aa-410b-86d0-9d4455bdbe6e)

**Comment by rsilvery** [comment]
Fair enough - but what I discussed with @neville today is that we really don't need to offer/expose every possible optional field in the UI. In the case of either/or, let's be opinionated. I think we decided to not go with the long-form URL so let's only show the field for host, if that's the correct one for the host name of the server, for example.

**Comment by galvana** [comment]
I'm tracking the required fields in Confluence, closing this ticket.

**Comment by Roger-Ethyca** [comment]
moving to done
