### ISSUE TITLE
fix broken migration for `system.legal_basis_*` `null` values

### ISSUE THREAD

**Issue by adamsachs** [ethyca/fides#3998]
### Bug Description

based on local testing, it seems like [this line](https://github.com/ethyca/fides/pull/3977/files#diff-d8a92bd01c9fae4ad5f9e9915de2344eac23f1939b3de0496d466d919d051831R112) in the migration isn't working as expected -- after upgrading from `a8` to `a10`, i ended up with `[NULL]` values in these columns on my DB, and the `GET /system` API was throwing a `500` (since it's not expecting a list with `None` as a value)

#### Steps to Reproduce

- [ ] run `fides` before the migration, create a system with no `legal_basis_for_profiling` or `legal_basis_for_transfers` value
- [ ] don't clear volumes/db and run `fides` after the migration - check values

### Expected behavior

_A description of what you expected to happen._

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by pattisdr** [comment]
dug into this some since I reviewed the initial migration.  I don't think this is an issue - we had a branch on a deployed environment, then deployed a new branch that had bumped the downrev of a migration that had already occurred.  The referenced migration never got a chance to run, so we were in a weird state there.

**Comment by adamsachs** [comment]
thanks again for the follow up on this @pattisdr, really appreciate the diligence 🙏
