### ISSUE TITLE
No caching/prefetch available for regions without privacy notice(s)

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fides#4108]
### Bug Description

When not in a location that has a privacy notice, the experience is returned as an empty object. This empty object is not cached, resulting in the privacy experience endpoint being hit for any user coming from a region that doesn't have a privacy notice.

#### Steps to Reproduce

1. Use a prefetch enabled privacy center and `fides.js` via the CDN
1. Ensure the location you are in does not have a valid privacy notice
2. Go to the URL where fides.js is installed (i.e. Cookie House) and inspect the Network responses, filtering for `fides`
3. View the experiences and see that none are returned. Additionally, note that the cache cannot be used where no experience exists

### Expected behavior

Be able to use the cache for a region without a privacy notice.

### Screenshots

n/a

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

This was found while investigating an issue, it turned out the privacy notice itself had been disabled because the sole system/data use driving it had been removed. This could be another related symptom of not having a privacy notice returned by default

**Comment by NevilleS** [comment]
Pretty sure it's just this behaviour: https://github.com/ethyca/fides/blob/0f74db23b3686215cde609075b61935426efe927/clients/fides-js/src/services/fides/api.ts#L61

For the purposes of prefetching, any `response.ok` should be treated as success, but since we're (effectively) mapping an successful result that found an empty list to `null`, it acts as if the prefetch failed.

**Comment by Roger-Ethyca** [comment]
moving to done
