### ISSUE TITLE
Replace `fides-js` direct calls to gvl.json with datamap data instead

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#4285]
### Is your feature request related to a specific problem?

There are 4 areas in `fides-js` where we still query the `gvl.json` directly:
* [x] Stacks
* [ ] Data categories
* [x] Privacy policy/Legitimate interest disclosure URLs
* [x] Cookie storage info
* [x] Data retention

### Describe the solution you'd like

We need to route this data from the backend to the `/privacy-experience` endpoint so that the TCF overlay can render this.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

Cookie storage info and privacy policy/legitimate interest disclosure urls can be done as part of https://github.com/ethyca/fides/issues/4255

**Comment by adamsachs** [comment]
noting that:
- Privacy policy/Legitimate interest disclosure URLs
- Cookie storage info

are already present on the BE artifacts and are being populated (or can easily be populated) on the TCF overlay payload from the BE. @allisonking is working on those currently.

the first two items: 
- Stacks
- Data categories
could be moved to the BE and implemented relatively easily if we want to continue using the raw gvl.json directly (on the BE). if we do not want to rely on the raw gvl.json (since that seems to be a general technical preference), there implementation could be significantly more complex.

**Comment by adamsachs** [comment]
will move this whole ticket over to jira, but update from conversation on 10/24 between @Kelsey-Ethyca @rsilvery @mfbrown :

we've already got these being read from the datamap
- Privacy policy/Legitimate interest disclosure URLs
- Cookie storage info
- Data retention

That leaves, from the original list:
- Stacks
- Data categories

with _stacks_, we're OK with having that read from the gvl.json for now since it's a GVL-defined concept, and it's not something we can derive fully from our `System` records. ideally we'd have the BE making the "stacks" calculation (also based on the GVL json) but that's not a high-priority at the moment to move that from the FE to the BE, since the FE needs the gvl.json regardless, to use for the `@iabtcf` JS library

with data categories, there's some uncertainty on how we can conclusively derive this from the `System` records in the datamap. as it stands, GVL data categories to `fideslang` data categories have a many-to-many cardinality, so there's not a deterministic mapping of a given `fideslang` data category to a given GVL data category. if we want to derive the data categories shown in the TCF overlay directly from `System` records, then we need to be sure what GVL category a given `fideslang` data category on a `System` should be translated to. @rsilvery to look into this and provide direction.
