### ISSUE TITLE
Version isn't properly reported in the Docker container

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#483]
### Bug Description

Fidesctl thinks it is version 0 in Docker

#### Steps to Reproduce

1. Pull the docker image
2. open a shell
3. `fidesctl --version`

### Expected behavior

It should show the correct version

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

This is caused by the root git file not being available at the build time of the image

**Comment by sanders41** [comment]
The issue is the [get_versions](https://github.com/ethyca/fides/blob/9ef854a7f192e7c13bb084db12e75fca29c243d6/fidesctl/src/fidesctl/_version.py#L513) function that is used to set the package version uses the `.git` directory to determine the version and there is no `.git` directory in the docker image. This results in the function returning the version as [0+unknown](https://github.com/ethyca/fides/blob/9ef854a7f192e7c13bb084db12e75fca29c243d6/fidesctl/src/fidesctl/_version.py#L557) since it is not able to find the `git` directory.

Because of this I suspect the issue is not specific to docker. If you were to `pip install fidesctl` the `.git` directory would also not be present this way.

In theory you could fix the docker issue by including the `.git` directory in the image, but I see 2 issues with this. First the resulting image would be a little larger (maybe acceptable). Second the `.git` directory is a level up from the `Dockerfile` so a `docker build` would not allow this directory to be included.

**Comment by ThomasLaPiana** [comment]
@sanders41 yeah the options I was thinking of were:
1. Since we're using a Make command to build the image, and we run it from a directory up, we could mount the git dir at time of building
2. We could have it pull from git directly like you mentioned

I'm doing some Docker refactoring in #482 anyway so this should be easier to solve once that gets merged

**Comment by NevilleS** [comment]
Watching 👀
