### ISSUE TITLE
Bump Python to version 3.9

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#495]
### Is your feature request related to a specific problem?

Fidesops and Fidescls are currently both on Python 3.9. As they are both currently relying on fidesctl and we want our ecosystem to play nicely, we should update to version 3.9

### Describe the solution you'd like

Bump the Dockerfile Python version

### Describe alternatives you've considered, if any

Leaving as-is but testing to make sure our features work on both 3.8 and 3.9 using something like `tox` (this would be a good idea anyway though probably?)

### Additional context

There are various changes in 3.9 that might necessitate us updating some of our requirements as well

**Comment by sanders41** [comment]
Related to the tox question, fidesctl is pip installable from pypi with Python 3.7 through 3.10 as supported versions, from setup.py `python_requires=">=3.7, <4"`. However, only Python 3.8 running in Docker is tested in CI. It seems like it would be beneficial to have all supported Python version tested in CI.

**Comment by ThomasLaPiana** [comment]
agreed, but if we're covering 3.8 -> 3.10 we might as well stay on 3.8 so we don't accidentally use breaking features from 3.9

**Comment by sanders41** [comment]
If you are testing all supported Python versions in CI you can be confident all supported version work. At that point using any of the supported Python versions as the base in docker is fine, I don't think there is a right or wrong answer there (including saying with 3.8).

Either way I would suggest bumping the dependencies. Because the dependencies here are hard pined to to specific version, the current pined versions seem to be causing issues in newer Pythons. For example the current pinned version of Pydantic (I am assuming this is coming from the pinned version of FastAPI) starts breaking somewhere around Python 3.9.4.

**Comment by ThomasLaPiana** [comment]
going to investigate this as part of #518 , which would include multi-version python testing and thus a reworking of the pinned dependencies

**Comment by ThomasLaPiana** [comment]
Going to close this and instead open up an issue to make sure that we're testing across multiple python versions
