### ISSUE TITLE
Add the management UI to fidesctl

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#561]
### Is your feature request related to a specific problem?

Need to add components of the fides UI to fidesctl to enable development within the fidesctl project of the config UI

### Describe the solution you'd like

Add in all of the javascript infra needed to support a co-located python + js project

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by NevilleS** [comment]
We started discussing this a bit in Slack, but wanted to put some of my notes here for better stickiness:
* The fidesctl admin UI should be structured in exactly the same way as the admin UI from fidesops here: https://github.com/ethyca/fidesops/tree/main/clients/admin-ui
* Let's call the NextJS app `admin-ui` (just like fidesops), because it'll have pages for both the self-guided config UI but also the more general management pages for users, datasets, etc.
* There's going to be some inefficiencies and copypasta between the two admin UIs across the two projects, but I think we'll have to live with that. If we can find a good way to refactor out some NextJS libraries that get imported into both, that'd be great but not a dealbreaker yet

We also have several improvements we're looking to make on FidesUI, which you can see here: https://github.com/ethyca/fidesui/issues. One of those issues (https://github.com/ethyca/fidesui/issues) is the finishing touch so we can actually publish FidesUI as an open source repo 👍

**Comment by ThomasLaPiana** [comment]
@allisonking i assigned this to you as well to collaborate on getting this bootstrapped as needed :)

**Comment by allisonking** [comment]
Elliot did the initial copy this morning and walked me and Laura through it https://github.com/ethyca/fides/pull/624

**Comment by ThomasLaPiana** [comment]
@allisonking thank you for the update!

**Comment by LKCSmith** [comment]
@ThomasLaPiana - This can probably be closed, yeah? It looks like the above was merged 🙂

**Comment by ThomasLaPiana** [comment]
@LKCSmith good catch!
