### ISSUE TITLE
Some endpoints only work with a trailing slash

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#690]
### Bug Description

Some of our endpoints only work if they end with a trailing slash, i.e. `/api/v1/organization/` works, but `/api/v1/organization` results in a 404

#### Steps to Reproduce

1. Run `nox -s api`
1. Try to navigate to `localhost:8080/api/v1/organization`, which will give a 404
2. Navigate to `localhost:8080/api/v1/organization/` which should work as expected

### Expected behavior

For endpoints even without a trailing slash to work properly

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version: main
* OS: OSX
* Python Version: 3.8
* Docker Version: 20.10.14

### Additional context

Note that `/api/v1/health` does work, so this is probably a problem with dynamically generating the endpoints.

**Comment by sanders41** [comment]
The reason is the `/` in the root routes like [here](https://github.com/ethyca/fides/blob/8677c6fa8bc1fc6893836e43b3226412dc4e3c7a/src/fidesapi/routes/crud.py#L45). as opposed to the no trailing `/` like in [health](https://github.com/ethyca/fides/blob/764b732a2bb59619e976c832831c603400977651/src/fidesapi/main.py#L97). 

Changing to no `/` like ` @router.get("", response_model=List[resource_model], name="List")` makes `localhost:8080/api/v1/organization` work, but `localhost:8080/api/v1/organization/` will no longer work.

I thought newer version of FastAPI, including the version being used in fidesctl, were supposed to automatically handle this. I am not sure what that isn't happening.

**Comment by allisonking** [comment]
Another data point:
`http://localhost:8080/api/v1/dataset/demo_users_dataset` works, but `http://localhost:8080/api/v1/dataset/demo_users_dataset/` does not

**Comment by allisonking** [comment]
@ThomasLaPiana lemme know what you think about the fidesops solution above ^ and if it's something we want as well

**Comment by ThomasLaPiana** [comment]
@allisonking I'm doing some digging on the fidesops repo as I know plenty of other  people have run into this

Im playing around locally and will post my findings here :)
