### ISSUE TITLE
Prevent user from being able to some fields of the default taxonomy in UI

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#858]
### Is your feature request related to a specific problem?

~Users should not be given any UI indication that they can edit something that is part of the default taxonomy.~
Users should be allowed to enter the edit screen of the default taxonomy, and have certain fields editable, as specified int he comment below. 

The taxonomy section of the Fideslang docs should provide a good supplement of information about the type of each field, enum options, etc. https://ethyca.github.io/fideslang/taxonomy/overview/ 

### Describe the solution you'd like

~Do not render the edit button when a field is marked as part of the default taxonomy.~

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

Blocked by https://github.com/ethyca/fides/issues/854 https://github.com/ethyca/fides/issues/855 and https://github.com/ethyca/fides/issues/857

**Comment by mfbrown** [comment]
Scope Updates:
There are several components of the default taxonomy which should be editable, because they provide crucial data for the data map when applied to a system and/or dataset. 

**Data Categories**
Editable: Name, Description

**Data Use**
Editable: Name, Description, Legal Basis, Special Category, Recipient, Legitimate Interest, Legitimate Interest Impact Assessment

**Data Subject**
Editable: Name, Description, Rights, Strategy, Automated Decisions or Profiling.

We should also strike this requirement: "Do not render the edit button when a field is marked as part of the default taxonomy." which I have done above. 

Fides key, and parent key of the default taxonomy should remain immutable.

**Comment by ThomasLaPiana** [comment]
just a quick sidenote @mfbrown technically the fides_key is immutable, as changing the fides_key would create an entirely new object (unless they also went and specifically deleted the old one), and the parent_key should break if formatted incorrectly so that also might not be an issue 🤔 i.e.

if the `fides_key` is `user.generated.random`
the `parent_key` will _always_ be `user.generated`, it should error if it is anything else

**Comment by allisonking** [comment]
Based on @ThomasLaPiana 's comment, it sounds like we don't have to do anything special to prevent editing `fides_key` or `parent_key` on the backend. On the frontend, we can just have those fields be read-only. So I believe the changes needed for the backend, which were started in [this PR](https://github.com/ethyca/fides/pull/990) and covered in [this ticket](https://github.com/ethyca/fides/issues/986), would be:
* [ ] Do not allow modifying the `is_default` field via the API

Actually I think that's the only change? Assuming we are okay with what Thomas said, that you can't actually modify a fides key since it'd create a new object (and the parent key is pretty much derived from the fides key... kind of?). Otherwise, we could also change the logic in https://github.com/ethyca/fides/pull/990 which was preventing all default taxonomy changes to _only_ prevent changes to `parent_key` (since changing `fides_key` is not really a thing)

However, @SteveDMurphy brings up a really good point about the default taxonomy being reloaded every time... it sounds like there are a few ways around this, and I'm not sure which way we'd want to go:
* Just don't allow modifying the default taxonomy at all, and make people extend the default (easiest, but perhaps not great UX?)
* Don't upsert the default taxonomy every time the server restarts. It probably wouldn't be difficult to remove this logic, but it'd be difficult to update the default taxonomy in the future on deployed instances
* other??

Until we decide on this, https://github.com/ethyca/fides/issues/986 is blocked

**Comment by ThomasLaPiana** [comment]
quick confirmation that the `parent_key` is derived directly from the `fides_key`, we have a validation check that they match

**Comment by allisonking** [comment]
The edit forms already make `fides_key` and `parent_key` read only. I think the only thing that needs to be done here now is, after https://github.com/ethyca/fides/pull/1006, to only render the delete button on non-default taxonomy objects, since we decided that default taxonomy objects can't be deleted
